AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: true

  Include:
    - spec/**/*.rb
    - lib/**/*.rb

  Exclude:
    - vendor/**/*

require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake
  - rubocop-disable_syntax

Style/DisableSyntax:
  DisableSyntax:
    - endless_methods

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb
    - "*.gemspec"

RSpec/NamedSubject:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/NumberedParametersLimit:
  Max: 2

Naming/FileName:
  Exclude:
    - cryptoform

RSpec/MultipleExpectations:
  Enabled: false
