#!/usr/bin/env ruby
# frozen_string_literal: true

ENV["APP_ENV"] = "production"

require "cryptoform"

class CryptoformCLI < Thor
  class << self
    def exit_on_failure?
      false
    end
  end

  include Cryptoform::CLI::Server
  include Cryptoform::CLI::Validate
  include Cryptoform::CLI::Init

  default_command :server

  no_commands do
    def cryptofile_path
      options[:cryptofile]
    end
  end
end

CryptoformCLI.start(ARGV)
