name: Release

on:
  release:
    types:
      - created

jobs:
  gem:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Build gem
        run: gem build

      - name: Create credentials
        run: |
          mkdir ~/.gem
          cat << EOF > ~/.gem/credentials
          ---
          :rubygems_api_key: ${{ secrets.RUBYGEMS_TOKEN }}
          EOF
          chmod 0600 /home/runner/.gem/credentials

      - name: Push gem
        run: gem push *gem

  docker:
    name: Docker

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version components
        id: extract-version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          IFS='.' read -r -a VERSION_PARTS <<< "${VERSION}"
          major="${VERSION_PARTS[0]}"
          minor="${VERSION_PARTS[1]}"
          patch="${VERSION_PARTS[2]}"

          echo "major=${major}" >> "$GITHUB_OUTPUT"
          echo "minor=${minor}" >> "$GITHUB_OUTPUT"
          echo "patch=${patch}" >> "$GITHUB_OUTPUT"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}
          MAJOR: ${{ steps.extract-version.outputs.major }}
          MINOR: ${{ steps.extract-version.outputs.minor }}
          PATCH: ${{ steps.extract-version.outputs.patch }}
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.MAJOR }},
            ${{ env.IMAGE_NAME }}:${{ env.MAJOR }}.${{ env.MINOR }},
            ${{ env.IMAGE_NAME }}:${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}

          cache-from: type=gha
          cache-to: type=gha,mode=max
